INSERT INTO Events (name, description, createdAt, updatedAt) VALUES
('Inflação Global Acelera', 'Aumento generalizado nos preços reduz poder de compra e pressiona bancos centrais a subir juros.', NOW(), NOW()),
('Corte de Juros pelo Banco Central', 'Política monetária expansionista estimula economia.', NOW(), NOW()),
('Crise Geopolítica em País Exportador', 'Conflitos interrompem cadeias de suprimentos globais.', NOW(), NOW()),
('Adoção em Massa de Criptomoedas', 'Grandes empresas passam a aceitar criptomoedas como pagamento.', NOW(), NOW()),
('Colapso de uma Grande Empresa de Tecnologia', 'Queda de uma gigante do setor abala confiança no mercado.', NOW(), NOW()),
('Boom do Mercado Imobiliário', 'Demanda por imóveis supera oferta, elevando preços.', NOW(), NOW()),
('Pandemia Global (Nova Variante)', 'Lockdowns reduzem atividade econômica.', NOW(), NOW()),
('Regulamentação Restritiva a Criptomoedas', 'Governos impõem limites ao uso de criptoativos.', NOW(), NOW()),
('Commodities Agrícolas em Alta', 'Secas afetam produção de grãos e alimentos.', NOW(), NOW()),
('Avanço em Energia Limpa', 'Novas tecnologias reducem custos de energia renovável.', NOW(), NOW()),
('Crise Bancária Sistêmica', 'Grandes bancos enfrentam liquidez insuficiente.', NOW(), NOW()),
('Aumento de Investimentos em Startups', 'Capital de risco flui para inovações disruptivas.', NOW(), NOW()),
('Queda no Preço do Petróleo', 'Excesso de oferta derruba preços globais.', NOW(), NOW()),
('Fortalecimento do Dólar', 'Moeda americana ganha força frente a outras.', NOW(), NOW()),
('Nova Lei de Incentivo a Imóveis', 'Subsídios governamentais para compra de casas.', NOW(), NOW()),
('Hackers Atacam Exchange de Criptomoedas', 'Plataforma perde fundos em ataque cibernético.', NOW(), NOW()),
('Recessão em Economia Chave', 'Queda no PIB de grande economia global.', NOW(), NOW()),
('Oferta Pública Bem-Sucedida de Startup', 'IPO de startup valoriza setor de inovação.', NOW(), NOW()),
('Desastre Natural em Região Produtora', 'Furacão destrói plantações e infraestrutura.', NOW(), NOW()),
('Adoção de Bitcoin por País', 'Nações começam a aceitar BTC como moeda legal.', NOW(), NOW()),
('Crise no Setor de Construção', 'Falências de grandes construtoras.', NOW(), NOW()),
('Alta nos Salários Globais', 'Pressão inflacionária por aumento de renda.', NOW(), NOW()),
('Quebra de Corretora de Investimentos', 'Instituição financeira entra em colapso.', NOW(), NOW()),
('Acordo Comercial Global', 'Redução de tarifas entre grandes economias.', NOW(), NOW()),
('Escassez de Metais Industriais', 'Demanda por cobre e níquel supera oferta.', NOW(), NOW()),
('Regulamentação Favorável a Fintechs', 'Governo facilita inovações financeiras.', NOW(), NOW()),
('Queda no Consumo de Luxo', 'Recessão reduz gastos com bens supérfluos.', NOW(), NOW()),
('Avanço em Inteligência Artificial', 'Novas tecnologias aumentam produtividade.', NOW(), NOW()),
('Greve em Setor Estratégico', 'Paralisação afeta produção de commodities.', NOW(), NOW()),
('Estabilização de Moeda Emergente', 'País em crise controla hiperinflação.', NOW(), NOW());

INSERT INTO Assets (name, type, liquidity, base_sale_time, slippage, current_value, createdAt, updatedAt) VALUES
('Ações', 'Mercado de Capitais', 90, 1, 0.40, 100.47, NOW(), NOW()),
('Ouro', 'Commodities', 70, 2, 0.80, 1758.57, NOW(), NOW()),
('Criptomoedas', 'Ativo Digital', 60, 2, 1.50, 70.70, NOW(), NOW()),
('Imóveis', 'Real Estate', 40, 4, 2.50, 264.61, NOW(), NOW()),
('Títulos do Governo', 'Renda Fixa', 95, 1, 0.20, 687.31, NOW(), NOW()),
('Commodities', 'Mercado Global', 75, 2, 0.90, 667.12, NOW(), NOW()),
('Startups', 'Capital de Risco', 30, 3, 3.00, 4103.00, NOW(), NOW());

INSERT INTO EventAssetImpacts (impact, createdAt, updatedAt, event_id, asset_id) VALUES
(-0.03, NOW(), NOW(), 1, 1),
(0.05, NOW(), NOW(), 1, 2),
(-0.04, NOW(), NOW(), 1, 5),
(0.06, NOW(), NOW(), 2, 1),
(0.04, NOW(), NOW(), 2, 4),
(0.03, NOW(), NOW(), 2, 5),
(0.07, NOW(), NOW(), 3, 2),
(0.02, NOW(), NOW(), 3, 3),
(0.05, NOW(), NOW(), 3, 6),
(0.10, NOW(), NOW(), 4, 3),
(0.03, NOW(), NOW(), 4, 7),
(-0.08, NOW(), NOW(), 5, 1),
(-0.03, NOW(), NOW(), 5, 3),
(-0.05, NOW(), NOW(), 5, 7),
(0.04, NOW(), NOW(), 6, 1),
(0.07, NOW(), NOW(), 6, 4),
(0.06, NOW(), NOW(), 7, 2),
(-0.04, NOW(), NOW(), 7, 4),
(-0.05, NOW(), NOW(), 7, 6),
(0.02, NOW(), NOW(), 8, 2),
(-0.12, NOW(), NOW(), 8, 3),
(0.04, NOW(), NOW(), 9, 1),
(0.08, NOW(), NOW(), 9, 6),
(-0.03, NOW(), NOW(), 10, 6),
(0.05, NOW(), NOW(), 10, 7),
(-0.07, NOW(), NOW(), 11, 1),
(0.09, NOW(), NOW(), 11, 2),
(0.06, NOW(), NOW(), 11, 5),
(0.03, NOW(), NOW(), 12, 3),
(0.10, NOW(), NOW(), 12, 7),
(-0.04, NOW(), NOW(), 13, 1),
(-0.06, NOW(), NOW(), 13, 6),
(-0.04, NOW(), NOW(), 14, 2),
(-0.03, NOW(), NOW(), 14, 6),
(0.05, NOW(), NOW(), 15, 1),
(0.08, NOW(), NOW(), 15, 4),
(0.02, NOW(), NOW(), 16, 2),
(-0.15, NOW(), NOW(), 16, 3),
(-0.07, NOW(), NOW(), 17, 1),
(0.04, NOW(), NOW(), 17, 5),
(-0.05, NOW(), NOW(), 17, 6),
(0.05, NOW(), NOW(), 18, 1),
(0.12, NOW(), NOW(), 18, 7),
(-0.03, NOW(), NOW(), 19, 4),
(0.09, NOW(), NOW(), 19, 6),
(-0.03, NOW(), NOW(), 20, 2),
(0.15, NOW(), NOW(), 20, 3),
(-0.06, NOW(), NOW(), 21, 1),
(-0.08, NOW(), NOW(), 21, 4),
(0.04, NOW(), NOW(), 22, 1),
(0.03, NOW(), NOW(), 22, 6),
(-0.06, NOW(), NOW(), 23, 1),
(0.04, NOW(), NOW(), 23, 5),
(0.05, NOW(), NOW(), 24, 1),
(0.03, NOW(), NOW(), 24, 6),
(0.05, NOW(), NOW(), 25, 1),
(0.07, NOW(), NOW(), 25, 6),
(0.04, NOW(), NOW(), 26, 3),
(0.08, NOW(), NOW(), 26, 7),
(-0.03, NOW(), NOW(), 27, 2),
(-0.05, NOW(), NOW(), 27, 4),
(0.06, NOW(), NOW(), 28, 1),
(0.09, NOW(), NOW(), 28, 7),
(-0.04, NOW(), NOW(), 29, 1),
(0.06, NOW(), NOW(), 29, 6),
(0.05, NOW(), NOW(), 30, 1),
(0.05, NOW(), NOW(), 30, 5);